services:
  backend:
    build: .
    ports:
      - "${PORT}:4000"  # Mapea el puerto 4000 del host al 4000 del contenedor
    environment:
      - MONGODB_URI=${MONGODB_URI}  # Usa la variable de entorno del archivo .env
      - JWT_SECRET=${JWT_SECRET}
      - PORT=4000  # Fijo dentro del contenedor
    volumes:
      - ./uploads:/app/uploads  # Persiste las imágenes subidas